create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  table_number integer not null unique,
  name text not null,
  people integer not null,
  phone text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint people_positive check (people > 0)
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists reservations_set_updated_at on public.reservations;
create trigger reservations_set_updated_at
before update on public.reservations
for each row execute function public.set_updated_at();

alter table public.reservations enable row level security;

drop policy if exists "Anyone can read reservations" on public.reservations;
create policy "Anyone can read reservations"
on public.reservations
for select
to anon
using (true);

drop policy if exists "Anyone can create reservations" on public.reservations;
create policy "Anyone can create reservations"
on public.reservations
for insert
to anon
with check (true);

drop policy if exists "Anyone can update reservations" on public.reservations;
create policy "Anyone can update reservations"
on public.reservations
for update
to anon
using (true)
with check (true);

drop policy if exists "Anyone can delete reservations" on public.reservations;
create policy "Anyone can delete reservations"
on public.reservations
for delete
to anon
using (true);
